name: expect_better
description: Better assertions, but still using dart test library. Better readability and discovery when using code completion, without compromises.
version: 1.2.0
repository: https://github.com/gbassisp/expect_better

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  lean_extensions: ^1.9.1
  meta: ^1.15.0
  test: ^1.25.0

dev_dependencies:
  very_good_analysis:
